Set queue family index to 0 on creating buffer and image during replaying
LunarG/gfxreconstruct pull request #1090
Opened 2023-04-14 16:47 UTC by locke-lunarg

When the trimming capturing initizes, it needs to deal with buffers and images on ProcessBufferMemory and ProcessImageMemory. But when the buffers and images are created with queue family index not 0, it might happen DeivceLost on QueueWaitIdle or QueueSubmit.

2023-04-17 16:41 UTC, locke-lunarg commented
https://github.com/LunarG/Projects/issues/528
For this issue, it always failed during trimming capturing. The reason is `Device_Lost` on `WaitForQueue`. The queue's family index is 1. I figured out if I changed it to 0, the trimming will success. Honestly, I don't exact know why it happens `Device_Lost`, and I'm not sure if it's a good idea to change it to 0.

2023-04-18 13:18 UTC, andrew-lunarg requested changes
I don't think we can just lie to the Vulkan implementation and say all these buffers and images are only used on queue family zero. It might help one particular troublesome trace on a particular implementation but it will break other traces and other implementations.

At a minimum, I think it should be hidden behind a flag and only turned on optionally, but even then it really doesn't make sense to me.

For traces with queue family trouble, I'd suggest implementing my issue https://github.com/LunarG/gfxreconstruct/issues/949 and then recapturing them so that they really do only use queue family zero.

2023-04-18 13:18 UTC, andrew-lunarg commented on framework/decode/vulkan_replay_consumer_base.cpp
> +    VkBufferCreateInfo                    modified_create_info        = *replay_create_info;
We used to have a null check on line 4220 but now we trust this isn't null. Is that safe?

2023-04-18 13:18 UTC, andrew-lunarg commented on framework/decode/vulkan_replay_consumer_base.cpp
> +        modified_create_info.queueFamilyIndexCount = 1;
I don't think we can assert that all buffers with concurrent usage only use the first queue family. This is a lie for traces in which buffers are used by multiple families and violates the Vulkan specification. 
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkBufferCreateInfo

2023-04-18 13:18 UTC, andrew-lunarg commented on framework/decode/vulkan_replay_consumer_base.cpp
> +    {
Same point as for buffers.

2023-04-24 17:47 UTC, locke-lunarg commented
@andrew-lunarg  You're right. I agreed with you.

2023-05-23 20:07 UTC, closed without merging