Fix replay staging buffer binding for when the capture/replay devices are not the same.
LunarG/gfxreconstruct pull request #1115
Opened 2023-05-04 18:42 UTC by jacobv-nvidia

While testing the replay of trimmed capture files on devices other than the original capture device, I encountered an issue in the rebind allocator where allocations would fail, causing the replay to abort.

The initial loading allocations would fail, and, when running the replay with the `--validate` option, I would receive messages such as the following:
```
VUID-vkMapMemory-memory-00682(ERROR / SPEC): msgNum: -330527817 - Validation Error: [ VUID-vkMapMemory-memory-00682 ] Object 0: handle = 0x4b07580000000ca2, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xec4c8bb7 | Mapping Memory without VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set: VkDeviceMemory 0x4b07580000000ca2[]. The Vulkan spec states: memory must have been created with a memory type that reports VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-vkMapMemory-memory-00682)
    Objects: 1
	[0] 0x4b07580000000ca2, type: 8, name: NULL
```

The issue seems to be in the rebind allocator's "Direct"` binding functions, which are supposed to be performed without memory translation for the purposes of, for example, replay staging buffers. However, these functions were using the capture device's memory types instead of the replay device's.

This patch should fix the issue.

2023-05-04 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LunarG/gfxreconstruct?pullRequest=1115) it.</sub>

2023-05-04 19:51 UTC, andrew-lunarg reviewed
Looks like a very useful fix, so thanks for the PR!

One point, It might be cleaner to extend `BindBufferMemory` and `BindImageMemory` with the extra bool parameter and give it a default value of true. Then the two new functions with slightly vague names wouldn't be needed.

2023-05-04 20:21 UTC, jacobv-nvidia commented
Yes, I was on the fence about that. I was trying to avoid cluttering the parent interface of the more general class `VulkanResourceAllocator`. Do you think it's worth it?

2023-05-26 19:16 UTC, locke-lunarg approved these changes

2023-05-26 21:40 UTC, bradgrantham-lunarg requested changes
Thank you for this PR!  I have proposed a small change to the calling sequence in a comment.

2023-05-26 21:41 UTC, bradgrantham-lunarg commented
I tried to take a trimmed capture of vkcube from llvmpipe and replay it on NVIDIA with `--validate` but got no validation error for vkMapMemory from SDK 1.3.246's binaries.@jacobv-nvidia , what's a good test case for this?

2023-05-29 05:47 UTC, jacobv-nvidia commented on framework/decode/vulkan_rebind_allocator.cpp
> +            is_direct_allocation
Sure, go ahead. I agree, your new change seems like a much less hacky implementation of the fix.

2023-05-29 05:51 UTC, jacobv-nvidia commented
> I tried to take a trimmed capture of vkcube from llvmpipe and replay it on NVIDIA with `--validate` but got no validation error for vkMapMemory from SDK 1.3.246's binaries.@jacobv-nvidia , what's a good test case for this?

I have just successfully tested it with vkcube, so that should work as a good test case, but you do need to:
1. use the vkcube option `--use_staging`
2. avoid including the first frame as part of the trim.

For example: `python gfxrecon-capture-vulkan.py -o cube.gfxr --capture-frames 2-16 vkcube --use_staging`

I haven't really tested on llvmpipe, so can't speak too much on that part. The issue was discovered and tested using an NVIDIA trace on an AMD card, but I suppose it's possible that the relevant memory type indices just happen to match up between llvmpipe and NVIDIA.

2023-06-30 20:59 UTC, bradgrantham-lunarg commented
Merged as #1173.

We encountered this this week in our internal CI and this solved our problem so I prioritized it.

Thank you for finding this @jacobv-nvidia !

2023-06-30 20:59 UTC, closed without merging

2023-07-02 03:30 UTC, jacobv-nvidia commented
@bradgrantham-lunarg Apologies for the delay in responding, I thought I had replied to your earlier comment on your changes. Anyway, I appreciate the merge.