discard-cached-psos renamed to use_cached_psos
LunarG/gfxreconstruct pull request #1207
Opened 2023-07-20 14:49 UTC by igorbrsn

**Problem:**
The replayer should always use 'discard-cached-psos'. Currently '--dcp' and '--discard-cached-psos' are options and could not be disabled. 

**Solution:**
Added option'--use-cached-psos' with default 'false'. 'discard_cached_psos' renamed to 'use_cached_psos' and would be set 'true' if used.

**Test:**
Tested with default, enabled and disabled. Warning issued when deprecated '--dcp' is used.

2023-07-20 18:39 UTC, bradgrantham-lunarg commented
In general I think this is fine, probably "dcp" should be the default.  However, "dcp" means "discard cached PSOs".  "enable-dcp" would mean "enable discard cached PSOs", the same thing as "dcp".   If this change makes "discard cached PSOs" the default and adds an option to *not* discard the PSOs, then I think the option would be called "use-cached-psos" or some such.

2023-07-27 20:06 UTC, igorbrsn commented
> > In general I think this is fine, probably "dcp" should be the default. However, "dcp" means "discard cached PSOs". "enable-dcp" would mean "enable discard cached PSOs", the same thing as "dcp". If this change makes "discard cached PSOs" the default and adds an option to _not_ discard the PSOs, then I think the option would be called "use-cached-psos" or some such.
> 
> Changed to --use-cached-psos

I am updating logic

2023-07-28 18:55 UTC, bradgrantham-lunarg requested changes

2023-07-28 18:55 UTC, bradgrantham-lunarg commented on tools/tool_settings.h
> +        GFXRECON_LOG_WARNING("The parameters --dcp and --discard-cached-psos have been depracated in favor for "
"deprecated"

2023-07-28 18:55 UTC, bradgrantham-lunarg commented on USAGE_desktop_D3D12.md
> +                        [--use-cached-psos <boolean>] [--surface-index <N>]
I think it shouldn't be a boolean if it's off if you specify nothing but turned on when you specify it.  Making this a boolean would make it inconsistent with other command-line switches.

2023-07-28 18:55 UTC, bradgrantham-lunarg commented on framework/decode/dx12_replay_consumer_base.cpp
> +        if (options_.use_cached_psos == false)
I prefer `!options_.use_cached_psos` to checking for explicit false.

2023-07-31 18:46 UTC, davidd-lunarg requested changes
I've added a couple requests to fixup documentation for the new option. Also, please update the PR title and description to match the latest changes in the PR.

2023-07-31 18:46 UTC, davidd-lunarg commented on USAGE_desktop_D3D12.md
> +                               Disabling helps enable replay across changing driver installs.
Can this text be changed to give some more detail about why a user might or might not want to enable the flag, for example:
```
  --use-cached-psos   Permit using cached PSOs when creating graphics or compute pipelines.
                      Using cached PSOs may reduce PSO creation time but may result in replay errors.
```

`PrintUsage()` in `replay_settings.h` also needs to be updated to match whatever text is used here.

2023-07-31 19:11 UTC, davidd-lunarg approved these changes

2023-08-01 00:40 UTC, merged