Trimmed captures documentation
LunarG/gfxreconstruct pull request #1230
Opened 2023-08-17 12:04 UTC by panos-lunarg

2023-08-17 15:41 UTC, bradgrantham-lunarg commented on USAGE_android.md
> +To create a trimmed capture one of the trimmining options can be used.
^trimmining^trimming

2023-08-17 15:43 UTC, bradgrantham-lunarg commented on USAGE_android.md
> +For example on android there are the `debug.gfxrecon.capture_frames`, which specifies
"there is the `debug.gfxrecon.capture_frames` property"

2023-08-17 15:44 UTC, bradgrantham-lunarg commented on USAGE_desktop_Vulkan.md
> +There's also the `GFXRECON_CAPTURE_TRIGGER`. Each time the hot key is pressed a,
^a,^a

2023-08-17 15:44 UTC, bradgrantham-lunarg commented on USAGE_desktop_Vulkan.md
> +the frame ranges to capture, each region generating a separate trimmed capture file.
^region^range

2023-08-17 15:50 UTC, bradgrantham-lunarg requested changes
Added some small nits and a suggestion for trimming an existing capture.

2023-08-17 15:50 UTC, bradgrantham-lunarg commented on USAGE_desktop_Vulkan.md
> +An existing capture can be trimmed by essentially enabling the gfxr
How about something like:

An existing capture file can be trimmed by replaying the capture with the capture layer enabled and a trimming frame range or trimming hot key enabled.  (However, replay for some content may be fast enough using the hot key may be difficult.)  Here's an example command-line that replays an existing capture with the capture layer enabled and configured to capture only from frame 100 through frame 200 into a new capture file:

`gfxrecon-capture.py -f 100-200 gfxrecon-replay gfxrecon-example-capture.gfxr`

2023-08-21 07:53 UTC, panos-lunarg commented on USAGE_android.md
> +Trimmed captures are created when GFXR is configured to start capturing not
I didn't specify granularity on purpose since we have a PR in flight that will fine grain this down to submission level

2023-08-22 21:12 UTC, bradgrantham-lunarg commented on USAGE_android.md
> +Trimmed captures are created when GFXR is configured to start capturing not
Fair enough.  But "start capturing not immediately" reads weirdly to me, so how about something like "start capturing at some later time in execution"?

2023-08-23 16:59 UTC, bradgrantham-lunarg approved these changes

2023-08-24 07:01 UTC, merged

2023-08-28 20:28 UTC, andrew-lunarg commented on USAGE_android.md
> +some content may be fast enough using the trigger property may be difficult.)
> (However, replay for some content may be fast enough using the trigger property may be difficult.)
No parentheses needed. Also add a that:
However, replay for some content may be fast enough **that** using the trigger property may be difficult.

2023-08-28 20:29 UTC, andrew-lunarg commented on USAGE_android.md
> +For example on android there is the `debug.gfxrecon.capture_frames` property,
**A**ndroid

2023-08-28 20:31 UTC, andrew-lunarg commented on USAGE_desktop_D3D12.md
> +some content may be fast enough using the hot key may be difficult.) Here's an example
Same as for Android version.

2023-08-28 20:32 UTC, andrew-lunarg commented on USAGE_desktop_Vulkan.md
> +enabled and a trimming frame range or trimming hot key enabled. (However, replay for
Paras and "that".

2023-08-28 20:45 UTC, andrew-lunarg commented on USAGE_android.md
> +time in execution.
It's hard to write a tight definition of a trimmed capture. What about changing the above to:

"...configured to not start capturing at the first API command that it observes but later, potentially after many frames of rendering have been skipped. In order to allow replay to also skip to the trim point capture writes a state dump at the start of the capture file, which replay can load."

_Sorry, I'm writing on a merged PR. Leaving these comments here for me to turn into a PR on top of this PR later._