support AGS 6.2.0
LunarG/gfxreconstruct pull request #1439
Opened 2024-03-05 21:22 UTC by igorbrsn

**The problem**
New AGS 6.2 version support is not supported.

**The solution**
6.2 changes are:

added `shaderClock`.
warning in capture if major version is not supported.
replay warning message if version is not 6.2.0.
backward compatibility supported - we still can replay 6.0.1 captures. We also can capture and replay 6.0.1 version.   
ags.lib and agsd.lib updated to 6.2.0

**Result**
Based on my testing I was able to capture and replay both Full and Trimmed version of 6.2 and 6.0 AGS

2024-03-05 21:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1439) before we can accept your contribution.<br/><hr/>**Igor Brusentsev** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LunarG/gfxreconstruct?pullRequest=1439) it.</sub>

2024-03-06 17:10 UTC, lunarpapillo commented
CI failure seems to be due to a busy machine.  Re-running.

2024-03-06 17:42 UTC, davidd-lunarg requested changes

2024-03-12 18:08 UTC, davidd-lunarg approved these changes

2024-03-12 21:45 UTC, merged