Fix 1359 - Update gfxrecon-convert's README.md
LunarG/gfxreconstruct pull request #1458
Opened 2024-03-22 13:02 UTC by nickdriscoll-lunarg

Issue #1359 pointed out that gfxrecon-convert's documentation was missing features, was outdated in the schema it described and showed in examples, and failed to mention D3D12 at all.

This PR updates the README.md such that it covers the missing features, the examples and explanations of the output schema are consistent with the tool's current behavior, and D3D12 is mentioned with examples when appropriate.

2024-03-26 00:23 UTC, bradgrantham-lunarg requested changes

2024-03-26 00:23 UTC, bradgrantham-lunarg commented on tools/convert/README.md
> +The tool's output is an ordered list of JSON structures, one per line in `--format jsonl` mode, each line a valid
Could you clarify this a hair?  Maybe separate out the tool's output in default `json` mode versus `jsonl` mode; maybe something like:
```
The tool's output in default `json` mode is an ordered list of JSON structures, or a single JSON structure per line in `--format jsonl` mode.  Each structure represents metadata, a metadata command, or a graphics API function or method call.  Below are the first few lines from a capture of vkcube with convert applied with `--format jsonl`, truncated to 200 columns.
```

2024-03-26 00:23 UTC, bradgrantham-lunarg commented on tools/convert/README.md
> +The tool's output is an ordered list of JSON structures, one per line in `--format jsonl` mode, each line a valid
Are all the subsequent examples either an extract of one structure from the JSON list or a pretty-print of a line from JSONL?  Could you add that as a note?

2024-03-26 00:23 UTC, bradgrantham-lunarg commented on tools/convert/README.md
> +gfxrecon-convert --output stdout vkcube.f1.gfxr | egrep -v "^{\"header\":{\"" | jq -c '.function.args = (.function.args | to_entries | map_values(.value))'
I think this example and other examples may need to be updated to add `--format jsonl` when appropriate

2024-03-26 00:23 UTC, bradgrantham-lunarg commented on tools/convert/README.md
> +gfxrecon-convert --output stdout vkcube.f1.gfxr | jq  -c "[.. | objects | keys[]] | unique" | sed "s/\"args\",//" | sed "s/\"index\",//" | sed "s/\"name\",//" | sed "s/\"return\",//" | sed "s/,\"func
I think this example needs `--format jsonl`.  I didn't check any further; could you verify whether the examples need `--format jsonl` or not?

2024-03-26 16:31 UTC, nickdriscoll-lunarg commented
Clarified line 58 and added "--format jsonl" to the examples that needed it.

2024-03-27 17:18 UTC, bradgrantham-lunarg approved these changes

2024-03-28 17:41 UTC, merged