modify copy resource message
LunarG/gfxreconstruct pull request #1678
Opened 2024-08-21 18:43 UTC by jirongjiao

Modify copy resource message to only log error when required subresource size is less than the actual subresource and log warning message in debug mode

2024-08-21 18:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/LunarG/gfxreconstruct?pullRequest=1678) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Jirong Jiao<br/>:x: jirongjiao<br/><hr/>**Jirong Jiao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LunarG/gfxreconstruct?pullRequest=1678) it.</sub>

2024-08-21 19:44 UTC, davidd-lunarg requested changes

2024-08-21 19:44 UTC, davidd-lunarg commented on framework/graphics/dx12_resource_data_util.cpp
> +                GFXRECON_LOG_ERROR("The size of the data to be copied to the subresource does not match the size "
With the new `if` comparison, the error message could be more specific (modified parts in bold below):

"The size of the data to be copied to the subresource **is greater than the size of** the subresource's copyable footprint. **Not all data can be written to the subresource**. (data size = %" PRIu64 ", footprint size = %" PRIu64 ", subresouce index = %" PRIu32 ")."

2024-08-22 12:20 UTC, jirongjiao commented on framework/graphics/dx12_resource_data_util.cpp
> +                GFXRECON_LOG_WARNING("The size of the data to be copied to the subresource does not match the size "
yes

2024-08-27 20:23 UTC, davidd-lunarg approved these changes
These changes look good.

Some of the commit authors are not tied to a GitHub account so the CLA check is failing. The commit authors will need to be updated before it can be merged.

2024-08-29 20:40 UTC, closed without merging