Fix importing AHB memory with rebind
LunarG/gfxreconstruct pull request #1820
Opened 2024-10-20 22:10 UTC by ziga-lunarg

VMA does not support external memory. If memory is allocated with AHardwareBuffer we must manually allocate it in rebind

2024-10-21 03:25 UTC, bradgrantham-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +        const VkBaseOutStructure* pNext = reinterpret_cast<const VkBaseOutStructure*>(allocate_info->pNext);
Can you use `vulkan_struct_get_pnext` for this?

2024-10-30 22:44 UTC, bradgrantham-lunarg commented
@mikes-lunarg can you make a minute to look at this?  Thank you!

2024-10-30 23:46 UTC, mikes-lunarg requested changes

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +            allocate_info.memoryTypeIndex = memory_alloc_info->original_index;
This seems to make an assumption that the memory type index won't change between capture and replay. Do we need a TODO or an issue to make this smarter? The rebind allocator is supposed to be the "most portable"

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +            dedicatedAllocateInfo.sType = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO;
Is dedicated allocation always required for AHB import? Or are you just giving the driver extra info since you know it is dedicated?

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +                assert(allocate_info.memoryTypeIndex < replay_memory_properties_.memoryTypeCount);
I would expect the memory index bounds to be checked before allocating the memory instead of after.

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +                    }
This block looks duplicated from BindImageMemory, does it make sense to put it in a helper?

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +                    VkDeviceMemory memory        = bind_infos[i].memory;
Why initialize `memory` from `bind_infos`? It will just get overwritten.

2024-10-30 23:46 UTC, mikes-lunarg commented on framework/decode/vulkan_rebind_allocator.cpp
> +            result                        = functions_.allocate_memory(device_, &allocate_info, nullptr, &memory);
Would prefer not to reuse the input value `memory` to hold the new memory handle. Also it seems like we are going to leak this handle and never free it.

2025-01-07 17:23 UTC, bradgrantham-lunarg approved these changes

2025-01-09 13:13 UTC, merged