Beau null test driver
LunarG/gfxreconstruct pull request #1886
Opened 2024-11-25 22:44 UTC by beau-lunarg

2025-01-30 17:34 UTC, MarkY-LunarG commented on test/test_apps/shader-objects/app.cpp
> +    test_config->device_api_version_override = VK_MAKE_API_VERSION(0, 1, 3, 296);
FYI, you can just set build version to 0 in the future.  Not a big deal.

2025-01-30 17:45 UTC, MarkY-LunarG commented on test/verify-gfxr.h
> + */
A+ on the comment.  I wish we had more this clear.

2025-01-30 18:48 UTC, MarkY-LunarG approved these changes
I don't know about the YAML files so I can't say much about those.  But in general everything looks good.  Just a few questions, but nothing blocking approval.

2025-01-30 18:48 UTC, MarkY-LunarG commented on test/icd/README.md
> +This directory contains a mock ICD driver designed for validation layer testing.
Nit, not just for "validation layer testing"

2025-01-31 01:41 UTC, beau-lunarg commented on test/test_apps/shader-objects/app.cpp
> +    test_config->device_api_version_override = VK_MAKE_API_VERSION(0, 1, 3, 296);
The original known good GFXR file had this version as the version returned by the "driver".  When the SDK was updated in GFXR, the returned version changed, which meant the GFXR changed and broke the test.  This hooks into the Mock ICD to force a returned version.  I could have also just updated the known good GFXR, but this now is an example of how to interact with the Mock ICD.

2025-01-31 01:56 UTC, beau-lunarg commented on test/test_apps/common/test_app_base.cpp
> +
I do that so the loader knows which ICD to use.  However, I also need to load and configure the mock ICD before I create an Instance, so I load it here.

2025-02-17 23:10 UTC, bradgrantham-lunarg commented on test/test_apps/common/test_app_base.cpp
> -#endif
@beau-lunarg

2025-02-17 23:10 UTC, bradgrantham-lunarg commented on test/icd/README.md
> +This directory contains a mock ICD driver designed for validation layer testing.
@beau-lunarg

2025-02-17 23:41 UTC, bradgrantham-lunarg requested changes

2025-02-17 23:41 UTC, bradgrantham-lunarg commented on layer/json/VkLayer_gfxreconstruct.json.in
> +        "disable_environment": {
Wait, what is this?  Do we actually honor this?  I couldn't find it in our code or docs.

2025-02-17 23:41 UTC, bradgrantham-lunarg commented on TESTING_test_apps.md
> +To run the test apps and validate output against known good '.gfxr' files, build the project using ./scripts/build.py,
Is there a way to run the tests from inside Visual Studio or from a directory after building in VS?

2025-02-18 18:04 UTC, beau-lunarg commented on test/test_apps/common/test_app_base.cpp
> -#endif
This was causing issue with the portability of the GFXR files.  Now that MacOS has its own known good files, we should be able to add this back in.

2025-02-18 19:44 UTC, beau-lunarg commented on layer/json/VkLayer_gfxreconstruct.json.in
> +        "disable_environment": {
This is a required field in layer JSONs.  The Windows GitHub machine ignores the GFXR layer during app tests because this is missing, as can be seen here:
https://github.com/LunarG/gfxreconstruct/actions/runs/13398475430/job/37423282501?pr=1886

Disabling based on this env var is done in the loader, our code is not responsible.

2025-02-18 19:46 UTC, beau-lunarg commented on TESTING_test_apps.md
> +To run the test apps and validate output against known good '.gfxr' files, build the project using ./scripts/build.py,
./scripts/build.py isn't required.  Really you just need to run this from the install directory.  I've updated the instructions to be more clear.

2025-02-18 19:47 UTC, beau-lunarg commented on test/icd/README.md
> +This directory contains a mock ICD driver designed for validation layer testing.
This was a copied over file from the source mock ICD, and doesn't work in this context.  Removing.

2025-02-18 20:08 UTC, bradgrantham-lunarg commented on TESTING_test_apps.md
> +To run the test apps and validate output against known good '.gfxr' files, build the project using ./scripts/build.py,
If I just open gfxreconstruct.sln, then hit F7 to build, how do I run the tests?

2025-02-24 18:31 UTC, bradgrantham-lunarg approved these changes
LGTM with some clarification in https://github.com/beau-lunarg/gfxreconstruct/pull/1

2025-02-25 20:04 UTC, merged