just warn instead of fatal on different image index
LunarG/gfxreconstruct pull request #805
Opened 2022-09-14 23:09 UTC by bradgrantham-lunarg

The message was warning but the function was LOG_FATAL.  This caused an otherwise potentially workable capture to fail.  Instead, just LOG_WARNING.

2022-09-14 23:21 UTC, locke-lunarg commented
VulkanCapturedSwapchain::AcquireNextImage2KHR need to be modified, too.

2022-09-15 16:02 UTC, locke-lunarg requested changes
VulkanCapturedSwapchain::AcquireNextImage2KHR need to be modified, too.

2022-09-15 16:36 UTC, bradgrantham-lunarg commented
> VulkanCapturedSwapchain::AcquireNextImage2KHR need to be modified, too.

Good catch, thanks!  Fixed.

2022-09-15 17:03 UTC, locke-lunarg approved these changes

2022-09-15 18:34 UTC, merged