toascii - Minimal Change to Enable JSON Lines Output
LunarG/gfxreconstruct pull request #807
Opened 2022-09-15 18:51 UTC by andrew-lunarg

toascii - Minimal Change to Enable JSON Lines Output
Currently only addresses Issue #765.
Not quite done yet: There are manually-coded function to string conversions to be changed.
A Commit for 783 (JSON Lines) is to also follow.
The output is like the following examples.
```json
{
    "type": "vkCall",
    "index": 0,
    "name": "vkCreateInstance",
    "return": "VK_SUCCESS",
    "params": {
        "pCreateInfo": {
            "sType": "VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO",
            "pNext": null,
            "flags": 0,
            "pApplicationInfo": {
                "sType": "VK_STRUCTURE_TYPE_APPLICATION_INFO",
                "pNext": null,
                "pApplicationName": "android framework",
                "applicationVersion": 0,
                "pEngineName": "android framework",
                "engineVersion": 0,
                "apiVersion": 4198400
            },
            "enabledLayerCount": 1,
            "ppEnabledLayerNames": [
                "VK_LAYER_LUNARG_gfxreconstruct"
            ],
            "enabledExtensionCount": 10,
            "ppEnabledExtensionNames": [
                "VK_KHR_surface",
                "VK_KHR_android_surface",
                "VK_EXT_swapchain_colorspace",
                "VK_KHR_get_surface_capabilities2",
                "VK_EXT_debug_report",
                "VK_KHR_device_group_creation",
                "VK_KHR_external_fence_capabilities",
                "VK_KHR_external_memory_capabilities",
                "VK_KHR_external_semaphore_capabilities",
                "VK_KHR_get_physical_device_properties2"
            ]
        },
        "pAllocator": null,
        "[out]pInstance": 1
    }
}
{
    "type": "vkCall",
    "index": 1,
    "name": "vkEnumeratePhysicalDevices",
    "return": "VK_SUCCESS",
    "params": {
        "instance": 1,
        "[out]pPhysicalDeviceCount": 1,
        "[out]pPhysicalDevices": []
    }
}
{
    "type": "vkCall",
    "index": 2,
    "name": "vkEnumeratePhysicalDevices",
    "return": "VK_SUCCESS",
    "params": {
        "instance": 1,
        "[out]pPhysicalDeviceCount": 1,
        "[out]pPhysicalDevices": [
            2
        ]
    }
}
...
{
    "type": "vkCall",
    "index": 167023,
    "name": "vkCmdBindDescriptorSets",
    "params": {
        "commandBuffer": 76, 
        "pipelineBindPoint": "VK_PIPELINE_BIND_POINT_GRAPHICS",
        "layout": 1427,
        "firstSet": 0,
        "descriptorSetCount": 1,
        "pDescriptorSets": [
            1452
        ],
        "dynamicOffsetCount": 2,
        "pDynamicOffsets": [
            11531840,
            11531904
        ]
    }
}
{
    "type": "vkCall",
    "index": 167024,
    "name": "vkCmdBindVertexBuffers",
    "params": {
        "commandBuffer": 76,
        "firstBinding": 0,
        "bindingCount": 1,
        "pBuffers": [
            96
        ],
        "pOffsets": [
            28816
        ]
    }
}
{
    "type": "vkCall",
    "index": 167025,
    "name": "vkCmdBindIndexBuffer",
    "params": {
        "commandBuffer": 76,
        "buffer": 103,
        "offset": 509568,
        "indexType": "VK_INDEX_TYPE_UINT16"
    }
}
{
    "type": "vkCall",
    "index": 167026,
    "name": "vkCmdDrawIndexed",
    "params": {
        "commandBuffer": 76,
        "indexCount": 6, 
        "instanceCount": 1,
        "firstIndex": 18,
        "vertexOffset": 0,
        "firstInstance": 0
    }
}
{
    "type": "vkCall",
    "index": 167027,
    "name": "vkCmdEndRenderPass",
    "params": {
        "commandBuffer": 76
    }
}
{
    "type": "vkCall",
    "index": 167028,
    "name": "vkCmdPipelineBarrier",
    "params": {
        "commandBuffer": 76,
        "srcStageMask": 66560,
        "dstStageMask": 128,
        "dependencyFlags": 0, 
        "memoryBarrierCount": 0,
        "pMemoryBarriers": [],
        "bufferMemoryBarrierCount": 0,
        "pBufferMemoryBarriers": [],
        "imageMemoryBarrierCount": 1,
        "pImageMemoryBarriers": [
            {
                "sType": "VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER",
                "pNext": null,
                "srcAccessMask": 256,
                "dstAccessMask": 32,
                "oldLayout": "VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL",
                "newLayout": "VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL",
                "srcQueueFamilyIndex": 4294967295,
                "dstQueueFamilyIndex": 4294967295,
                "image": 270,
                "subresourceRange": {
                    "aspectMask": 1,
                    "baseMipLevel": 0,
                    "levelCount": 4294967295,
                    "baseArrayLayer": 0,
                    "layerCount": 4294967295
                }
            }
        ]
    }
}
...
{
    "type": "vkCall",
    "index": 167030,
    "name": "vkEndCommandBuffer",
    "return": "VK_SUCCESS",
    "params": {
        "commandBuffer": 76
    }
}
{
    "type": "vkCall",
    "index": 167031,
    "name": "vkQueueSubmit",
    "return": "VK_SUCCESS",
    "params": {
        "queue": 65,
        "submitCount": 1,
        "pSubmits": [
            {
                "sType": "VK_STRUCTURE_TYPE_SUBMIT_INFO",
                "pNext": null,
                "waitSemaphoreCount": 0,
                "pWaitSemaphores": [],
                "pWaitDstStageMask": [],
                "commandBufferCount": 1,
                "pCommandBuffers": [
                    76
                ],
                "signalSemaphoreCount": 1,
                "pSignalSemaphores": [
                    279
                ]
            }
        ],
        "fence": 77
    }
}
{
    "type": "vkCall",
    "index": 167032,
    "name": "vkGetFenceStatus",
    "return": "VK_SUCCESS",
    "params": {
        "device": 64,
        "fence": 75
    }
}
{
    "type": "vkCall",
    "index": 167033,
    "name": "vkResetFences",
    "return": "VK_SUCCESS",
    "params": {
        "device": 64,
        "fenceCount": 1,
        "pFences": [
            75
        ]
    }
}
{
    "type": "vkCall",
    "index": 167034,
    "name": "vkResetDescriptorPool",
    "return": "VK_SUCCESS",
    "params": {
        "device": 64,
        "descriptorPool": 773,
        "flags": 0
    }
}
...
{
    "type": "vkCall",
    "index": 167044,
    "name": "vkGetPastPresentationTimingGOOGLE",
    "return": "VK_SUCCESS",
    "params": {
        "device": 64,
        "swapchain": 268,
        "[out]pPresentationTimingCount": 0,
        "[out]pPresentationTimings": []
    }
}
{
    "type": "vkCall",
    "index": 167045,
    "name": "vkQueuePresentKHR",
    "return": "VK_SUBOPTIMAL_KHR",
    "params": {
        "queue": 65,
        "pPresentInfo": {
            "sType": "VK_STRUCTURE_TYPE_PRESENT_INFO_KHR",
            "pNext": {
                "sType": "VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE",
                "pNext": null,
                "swapchainCount": 1,
                "pTimes": [
                    {
                        "presentID": 334,
                        "desiredPresentTime": 417846455289518
                    }
                ]
            },
            "waitSemaphoreCount": 1,
            "pWaitSemaphores": [
                279
            ],
            "swapchainCount": 1,
            "pSwapchains": [
                268
            ],
            "pImageIndices": [
                1
            ],
            "pResults": []
        }
    }
}
{
    "type": "vkCall",
    "index": 167046,
    "name": "vkResetCommandBuffer",
    "return": "VK_SUCCESS",
    "params": {
        "commandBuffer": 74,
        "flags": 1
    }
}
{
    "type": "vkCall",
    "index": 167047,
    "name": "vkBeginCommandBuffer",
    "return": "VK_SUCCESS",
    "params": {
        "commandBuffer": 74,
        "pBeginInfo": {
            "sType": "VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO",
            "pNext": null,
            "flags": 1,
            "pInheritanceInfo": null
        }
    }
}
{
    "type": "vkCall",
    "index": 167048,
    "name": [...]

2022-09-15 19:56 UTC, andrew-lunarg commented on framework/decode/vulkan_ascii_consumer_base.cpp
> -    fprintf(file_, "{");
The braces surrounding the whole file previously.

2022-09-20 14:38 UTC, bradgrantham-lunarg requested changes

2022-09-20 14:38 UTC, bradgrantham-lunarg commented on framework/decode/vulkan_ascii_consumer_base.cpp
> +        FieldToString(strStrm, true, "type", toStringFlags, tabCount, tabSize, "\"vkCall\"");
Can the writing of `type`, `index`, `name` all be factored out into `WriteApiCallToFile` across this change?

2022-09-23 23:50 UTC, andrew-lunarg commented
PR 811 Was chosen ahead of this design.
<https://github.com/LunarG/gfxreconstruct/pull/811>

2022-09-23 23:50 UTC, closed without merging