don't assert on non-decoded and print null instead of ""
LunarG/gfxreconstruct pull request #815
Opened 2022-09-23 21:56 UTC by bradgrantham-lunarg

Fix #814

2022-09-23 22:36 UTC, andrew-lunarg commented on framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
> -                        assert(decoded_obj.decoded_value != nullptr);
Don't we want this in debug builds? Release users will never see this.

2022-09-23 22:52 UTC, andrew-lunarg requested changes
There are all the manual versions in `framework/decode/custom_vulkan_struct_decoders_to_string.cpp` too.

2022-09-23 23:48 UTC, bradgrantham-lunarg commented
It turns out that null is valid for the decoded value If encoding omitted
the output struct because of a failed result code.  I mentioned that
briefly in the linked issue. So that was asserting on a valid value.

On Fri, Sep 23, 2022, 3:36 PM Andrew Cox - LunarG ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
> <https://github.com/LunarG/gfxreconstruct/pull/815#discussion_r979103388>:
>
> > @@ -127,10 +127,9 @@ def generate_feature(self):
>                  body = inspect.cleandoc('''
>                      template <> std::string ToString<decode::Decoded_{0}>(const decode::Decoded_{0}& decoded_obj, ToStringFlags toStringFlags, uint32_t tabCount, uint32_t tabSize)
>                      {{
> -                        assert(decoded_obj.decoded_value != nullptr);
>
> Don't we want this in debug builds? Release users will never see this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LunarG/gfxreconstruct/pull/815#pullrequestreview-1119095088>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCLT7YVKSTDJHCWK2DA7DDV7YWG3ANCNFSM6AAAAAAQUK2RWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-23 23:49 UTC, bradgrantham-lunarg commented
Good catch! I will go add those.

On Fri, Sep 23, 2022, 3:52 PM Andrew Cox - LunarG ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> There are all the manual versions in
> framework/decode/custom_vulkan_struct_decoders_to_string.cpp too.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LunarG/gfxreconstruct/pull/815#pullrequestreview-1119101104>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCLT7YX2LI4CGVPGQKWVBDV7YYDZANCNFSM6AAAAAAQUK2RWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-24 00:03 UTC, bradgrantham-lunarg commented
> It turns out that null is valid for the decoded value If encoding omitted the output struct because of a failed result code. I mentioned that briefly in the linked issue. So that was asserting on a valid value.

🤔 Do we know in the codegen when a struct is only ever used as an output struct?  I assume we know when a parameter is an output in function codegen, so could we assert `decoded_value

2022-09-24 00:12 UTC, bradgrantham-lunarg commented on framework/generated/vulkan_generators/vulkan_struct_decoders_to_string_body_generator.py
>                          }}
I don't think so, since this is a valid value.

2022-09-24 01:42 UTC, merged