Merging decoders used by gfxrecon-info
LunarG/gfxreconstruct pull request #976
Opened 2023-01-30 16:44 UTC by igorbrsn

**Problem**
Driver and exe file info split between 2 decoders and consumers.  

**Solution**
Create one new decoder (`InfoDeoder`) and consumer (`InfoConsumer`) to contain both driver and info logic.

**Results + testing** 
The performance remained unchanged as confirmed by tests that involved capturing and replaying traces and displaying info.

2023-03-08 19:11 UTC, davidd-lunarg requested changes

2023-03-08 22:02 UTC, andrew-lunarg commented on framework/decode/info_consumer_base.h
> +class InfoConsumerBase
That's a good point. We usually use the `XConsumer` and `XConsumerBase` idiom when the base is manual code and the derived class is generated.

2023-03-21 20:50 UTC, davidd-lunarg requested changes

2023-03-21 20:50 UTC, davidd-lunarg commented on framework/decode/info_decoder.h
> -    virtual bool SupportsMetaDataId(format::MetaDataId meta_data_id) override { return true; }
Include `override` on virtual methods that override base class methods.

2023-03-21 20:50 UTC, davidd-lunarg commented on tools/info/main.cpp
> +        gfxrecon::decode::InfoConsumer info_consumer;
This `info_consumer` appears to be unused.

2023-03-22 21:39 UTC, davidd-lunarg approved these changes

2023-03-22 21:41 UTC, merged